//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Deniz/Developer/workspace/HolaMundoe/src/java/ios/HolaMundo.java
//
//  Created by Deniz on 2/20/13.
//

//#line 1 "/Users/Deniz/Developer/workspace/HolaMundoe/src/java/ios/HolaMundo.java"

#import "HolaMundo.h"

#line 3
@implementation JavaIosHolaMundo

@synthesize helloInEnglish = helloInEnglish_;
@synthesize helloInSpanish = helloInSpanish_;

- (id)init {
  if ((self = [super init])) {
    helloInEnglish_ = @"hello";
    helloInSpanish_ = @"hola!";
  }
  return self;
}

#line 13
- (void)sayHelloInEnglish {
#line 14
  NSLog(@"%@", helloInEnglish_);
}

#line 17
- (void)sayHelloInSpanish {
#line 18
  NSLog(@"%@", helloInSpanish_);
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  JavaIosHolaMundo *typedCopy = (JavaIosHolaMundo *) copy;
  typedCopy.helloInEnglish = helloInEnglish_;
  typedCopy.helloInSpanish = helloInSpanish_;
}

@end
