//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Deniz/Developer/workspace/HolaMundoe/src/java/ios/HolaMundo.java
//
//  Created by Deniz on 2/20/13.
//

#import "JreEmulation.h"

@interface JavaIosHolaMundo : NSObject {
 @public
  NSString *helloInEnglish_;
  NSString *helloInSpanish_;
}

@property (nonatomic, copy) NSString *helloInEnglish;
@property (nonatomic, copy) NSString *helloInSpanish;

- (id)init;
- (void)sayHelloInEnglish;
- (void)sayHelloInSpanish;
@end
