//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Deniz/Developer/workspace/RandomNumGenerator/RandomNumGenerator.java
//
//  Created by Deniz on 2/20/13.
//

#line 1 "/Users/Deniz/Developer/workspace/RandomNumGenerator/RandomNumGenerator.java"

#import "RandomNumGenerator.h"
#import "java/lang/Math.h"

#line 2
@implementation RandomNumGenerator

@synthesize low = low_;
@synthesize high = high_;

#line 5
- (id)initWithInt:(int)l
          withInt:(int)h {
  if ((self = [super init])) {
    low_ = l;
    high_ = h;
  }
  return self;
}

#line 10
- (int)returnRandomNumber {
#line 11
  double rn = (high_ - low_) * ([JavaLangMath random]);
#line 12
  int finalRN = low_ + (int) rn;
#line 13
  return finalRN;
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  RandomNumGenerator *typedCopy = (RandomNumGenerator *) copy;
  typedCopy.low = low_;
  typedCopy.high = high_;
}

@end
